/* This file is part of onnx2c.
 *
 * sauria/conv.h - Conv_sauria
 * Implementation of a convolution using the SAURIA hardware accelerator.
 * 
 * This node reads convolution configuration from a manifest file
 * generated by sauria_onnx_preprocess.py and emits calls to the
 * pre-generated SAURIA functions.
 */

#ifndef CONV_SAURIA_H
#define CONV_SAURIA_H

#include "../nodes/spatialfilter.h"
#include "../sauria_manifest.h"
#include <string.h>

namespace toC {

class Conv_sauria : public SpatialFilter {
public:
    Conv_sauria() {
        op_name = "Conv_sauria";
    }

    virtual void print_output_cell_init(std::ostream &dst, const std::string &y_idx) const override
    {
        // Not used - we override print() completely
    }
    
    virtual void print_output_cell_calc(
        std::ostream &dst,
        const std::string &x_idx,
        const std::string &w_idx,
        const std::string &y_idx) const override
    {
        // Not used - we override print() completely
    }
    
    virtual void print_output_cell_finalize(std::ostream &dst, const std::string &y_idx) const override
    {
        // Not used - we override print() completely
    }
    
    virtual void print(std::ostream &dst) const override
    {
        LOG(TRACE) << "Printing Conv_sauria node: " << onnx_name << std::endl;
        
        // Look up this convolution in the manifest
        const SauriaManifest& manifest = SauriaManifest::instance();
        const SauriaConvInfo* conv_info = manifest.getConvInfo(onnx_name);
        
        if (!conv_info) {
            // Fallback: emit error comment and generic call
            dst << "\t/* ERROR: Conv node '" << onnx_name << "' not found in SAURIA manifest */" << std::endl;
            dst << "\t/* Make sure the manifest was generated from the same ONNX model */" << std::endl;
            dst << "\t#error \"SAURIA convolution not found in manifest: " << onnx_name << "\"" << std::endl;
            return;
        }
        
        // Use the local variable names set in resolve():
        // - "x" for input (from name_input(0, "x"))
        // - "y" for output (from register_output(rv, "y"))
        // - weight_var from manifest (pre-generated in SAURIA [C,H,W,K] format)
        //
        // Note: We do NOT use the onnx2c-generated "w" variable because it has
        // ONNX weight ordering [K,C,H,W]. The manifest's weight_var points to
        // weights already reordered to SAURIA format [C,H,W,K] where K is contiguous.
        
        // Emit comment with convolution info
        dst << "\t/* SAURIA Conv: " << onnx_name << " */" << std::endl;
        dst << "\t/* Function: " << conv_info->function_name << " */" << std::endl;
        if (conv_info->is_depthwise) {
            dst << "\t/* Type: Depthwise, channels=" << conv_info->num_channels << " */" << std::endl;
        }
        if (!conv_info->C_tile_shape.empty()) {
            dst << "\t/* Tiling: C_out=" << conv_info->C_tile_shape[0];
            if (conv_info->C_tile_shape.size() > 1)
                dst << ", Ch=" << conv_info->C_tile_shape[1];
            if (conv_info->C_tile_shape.size() > 2)
                dst << ", Cw=" << conv_info->C_tile_shape[2];
            dst << ", C_in=" << conv_info->tile_cin;
            dst << ", X=" << conv_info->X_used << ", Y=" << conv_info->Y_used;
            dst << " */" << std::endl;
        }
        
        // Emit the function call
        // The generated SAURIA functions have signature:
        // int sauria_XXX(uint32_t input_addr, uint32_t weight_addr, uint32_t output_addr)
        //
        // Arguments:
        // - x: input tensor (local variable, ONNX ordering is fine for activations)
        // - weight_var: pre-generated weights in SAURIA format [C,H,W,K]
        // - y: output tensor (local variable)
        //
        // Bias handling (Approach A - hardware preload):
        // When bias is present, we memcpy a pre-broadcast bias buffer [K,H,W] into
        // the output tensor before calling SAURIA. With preload_en=1, SAURIA's DMA
        // reads this data into MEMC and accumulates the MAC result on top.
        dst << "\t{" << std::endl;
        
        // If bias exists, preload broadcast buffer into output tensor
        LOG(TRACE) << "Seeing if bias exists: " << std::endl;
        int num_inputs = get_number_of_inputs();
        std::string bbvar = conv_info->bias_broadcast_var;
        LOG(TRACE) << "num_inputs = " << num_inputs << ", bbvar = " << bbvar << std::endl;


        if (options.profiling) {
            dst << "#ifdef ENTRY_PROFILING" << std::endl;
            dst << "\t\tuint64_t _bias_t0 = get_cycles();" << std::endl;
            dst << "#endif" << std::endl;
            }
        // If convolution has bias, copy bias into output 
        if (get_number_of_inputs() == 3 && !conv_info->bias_broadcast_var.empty()
            && conv_info->bias_broadcast_var != "NULL") {
            LOG(TRACE) << "Adding bias broadcast for Conv_sauria node: " << onnx_name << std::endl;
            const Tensor *output = get_output_tensor(0);
            // output->data_dim is [N, C_out, H_out, W_out]
            int C_out = output->data_dim[1];
            int H_out = output->data_dim[2];
            int W_out = output->data_dim[3];
            int broadcast_size = C_out * H_out * W_out;
            
            dst << "\t\t/* Preload bias broadcast into output tensor for SAURIA preload_en */" << std::endl;

            dst << "\t\tmemcpy(y, " << conv_info->bias_broadcast_var
                << ", " << broadcast_size << " * sizeof(" << output->data_type_str() << "));" << std::endl;
            
        }
        // Otherwise zero the output tensor
        else {
            LOG(TRACE) << "Zeroing output tensor for Conv_sauria node: " << onnx_name << std::endl;
            const Tensor *output = get_output_tensor(0);
            // output->data_dim is [N, C_out, H_out, W_out]
            int C_out = output->data_dim[1];
            int H_out = output->data_dim[2];
            int W_out = output->data_dim[3];
            int output_size = C_out * H_out * W_out;

            dst << "\t\t/* Zero output tensor */" << std::endl;

            dst << "\t\tmemset(y, 0, " << output_size << " * sizeof(" << output->data_type_str() << "));" << std::endl;
        }
        if (options.profiling) {
            dst << "#ifdef ENTRY_PROFILING" << std::endl;
            dst << "\t\tprof_record(\" (bias) " << c_name() << "\", get_cycles() - _bias_t0);" << std::endl;
            dst << "#endif" << std::endl;
            }
        
        dst << "\t\tXil_DCacheFlush();" << std::endl;
        dst << "\t\tint _sauria_ret = " << conv_info->function_name << "(" << std::endl;
        dst << "\t\t\t(uint32_t)x," << std::endl;
        dst << "\t\t\t(uint32_t)" << conv_info->weight_var << "," << std::endl;
        dst << "\t\t\t(uint32_t)y" << std::endl;
        dst << "\t\t);" << std::endl;
        dst << "\t\tXil_DCacheInvalidate();" << std::endl;
        dst << "\t\tprintf(\" (debug) " << c_name() << " ret_val = %d\\n\", _sauria_ret);" << std::endl;
        dst << "\t\tif (_sauria_ret != 0) {" << std::endl;
        dst << "\t\t\t/* SAURIA timeout or error */" << std::endl;
        dst << "\t\t\treturn;" << std::endl;
        dst << "\t\t}" << std::endl;
        dst << "\t}" << std::endl;
    }

    virtual void resolve(void) override
    {
        // Look up this convolution in the manifest
        const SauriaManifest& manifest = SauriaManifest::instance();
        const SauriaConvInfo* conv_info = manifest.getConvInfo(onnx_name);

        name_input(0, "x");
        name_input(1, "w");
        if (get_number_of_inputs() == 3) {
            name_input(2, "bias");
        }

        resolve_strides();
        resolve_dilations();
        resolve_pads();
        resolve_kernel_shape();

        Tensor *rv = new Tensor;
        rv->data_dim = resolve_output_size();
        rv->data_type = get_input_tensor(0)->data_type;
        register_output(rv, "y");
        
        // Only suppress weights if conv is in manifest
        if (!conv_info) {
            LOG(ERROR) << "Conv_sauria: '" << onnx_name << "' not found in manifest!" << std::endl;
            return;  // Let print() handle the error
        }
        
        Tensor *w_tensor = const_cast<Tensor*>(get_input_tensor(1));
        if (w_tensor) {
            w_tensor->generate = false;
            w_tensor->cname_override = conv_info->weight_var;
            w_tensor->initialize = false;
        }
        
        if (get_number_of_inputs() == 3) {
            Tensor *b_tensor = const_cast<Tensor*>(get_input_tensor(2));
            if (b_tensor) {
                b_tensor->generate = false;
                b_tensor->cname_override = conv_info->bias_var;
                b_tensor->initialize = false;
            }
        }
    }
};

} // namespace toC

#endif // CONV_SAURIA_H