/* This file is part of onnx2c.
 *
 * sauria_manifest.h
 * Loader for SAURIA convolution manifest generated by sauria_onnx_preprocess.py
 */

#ifndef SAURIA_MANIFEST_H
#define SAURIA_MANIFEST_H

#include <string>
#include <map>
#include <vector>

namespace toC {

struct SauriaConvInfo {
    std::string function_name;
    std::string weight_var;
    std::string bias_var;      // empty if no bias
    std::string bias_broadcast_var;      // empty if no bias
    std::string input_tensor;
    std::string output_tensor;
    bool is_depthwise;
    int num_channels;          // for depthwise conv, -1 otherwise
    
    // Tiling info (for comments/debugging)
    std::vector<int> C_tile_shape;
    int tile_cin;
    int X_used;
    int Y_used;
};

class SauriaManifest {
public:
    // Singleton access
    static SauriaManifest& instance();
    
    // Load manifest from JSON file
    bool load(const std::string& filepath);
    
    // Check if manifest is loaded
    bool isLoaded() const { return loaded; }
    
    // Look up convolution by ONNX node name
    // Returns nullptr if not found
    const SauriaConvInfo* getConvInfo(const std::string& node_name) const;
    
    // Get model name
    const std::string& getModelName() const { return model_name; }
    
    // Get hardware config name
    const std::string& getHardwareConfig() const { return hardware_config; }

private:
    SauriaManifest() : loaded(false) {}
    
    bool loaded;
    std::string model_name;
    std::string hardware_config;
    std::map<std::string, SauriaConvInfo> convolutions;
};

} // namespace toC

#endif // SAURIA_MANIFEST_H
